### ISSUE TITLE
Possibly Missing Step in Instructions?

### ISSUE THREAD

**Issue by Sewdohe** [kdrag0n/android_packages_apps_RepainterServicePriv#1]
I followed the instructions in the readme, but the last step I don't have an app.mk file as in the example commit. If I add 

```
# Repainter integration
PRODUCT_PACKAGES += \
    RepainterServicePriv \
```

anywhere else I see the variable occur, I get the following error:

```
[ 99% 227/228] finishing build rules ...
FAILED:
build/make/core/artifact_path_requirements.mk:26: warning:  build/make/target/product/generic_system.mk produces files outside its artifact path requirement. Allowed paths are root/*, system/*
Offending entries:
system_ext/etc/permissions/privapp_whitelist_dev.kdrag0n.dyntheme.privileged.sys.xml
system_ext/priv-app/RepainterServicePriv/RepainterServicePriv.apk
system_ext/priv-app/RepainterServicePriv/oat/arm64/RepainterServicePriv.odex
system_ext/priv-app/RepainterServicePriv/oat/arm64/RepainterServicePriv.vdex
In file included from build/make/core/main.mk:1346:
build/make/core/artifact_path_requirements.mk:26: error: Build failed.
22:31:42 ckati failed with: exit status 1
```

Am I simply dense to something obvious, or is there a step missing in the instructions? After some googling I found [this](https://source.android.com/devices/bootloader/partitions/product-interfaces) link that seems relevant, but not sure how it ties in.

I do dearly apologize if this doesn't constitute as an actual issue .

**Comment by kdrag0n** [comment]
Either [disable artifact path requirements](https://github.com/ProtonAOSP/android_build_make/commit/d64895f6b9) as a workaround or add it to a makefile that's meant for /system_ext. Different product makefiles are supposed to include build rules for different partitions; the one you added it to, generic_system.mk, is only for /system.
